all:	compile run

compile:	exo_1.c exo_2.c exo_3.c exo_5.c
	gcc exo_1.c -o exo_1.exe
	gcc exo_2.c -o exo_2.exe
	gcc exo_3.c -o exo_3.exe
	gcc exo_5.c -o exo_5.exe

run:	
	./exo_1.exe
	./exo_2.exe
	./exo_3.exe
	./exo_5.exe 5 2.0
	./exo_5.exe 5 3.4